export { ReduxProvider as default, ReduxProvider } from './components/ReduxProvider'
export { Provider, ProviderProps } from './components/Provider'
export { withTranslate } from './hoc/withTranslate'
export { setLanguage } from './redux/actions'
export { i18nReducer } from './redux/reducer'
